apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernates-spring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/djuybu/k8s-manifests.git'  # Repo GitOps của bạn
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
